name: Build APK & IPA(iOS26.5)
on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: flutter build apk --debug
      - uses: actions/upload-artifact@v5
        with:
          name: Android_APK
          path: build/app/outputs/apk/debug/*.apk

  build_ios:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - uses: subosito/flutter-action@v2
      - run: flutter pub get
      - run: cd ios && pod install --repo-update
      - run: flutter build ipa --debug --target-platform=ios-arm64
      - uses: actions/upload-artifact@v5
        with:
          name: iOS_IPA_26.5
          path: build/ios/ipa/*.ipa
